#!/bin/bash 
#PBS -l walltime=48:00:00
#PBS -l ncpus=16
#PBS -l mem=3GB
#PBS -l jobfs=10GB
#PBS -P hu38
#PBS -q normal
#PBS -l software=VinaCarb
#PBS -l wd

export VINA_CARB=../../VC_1_0

for folder in small/*LIGAND*;
    do
        ../../vina-carb --receptor /$folder/*Without* --ligand /$folder/*pdb.mol2* --config /$folder/*.conf --out /$folder/$folder.txt --log $folder/log_$folder.txt
    done

