#!/bin/bash 
#PBS -l walltime=48:00:00
#PBS -l ncpus=16
#PBS -l mem=3GB
#PBS -l jobfs=10GB
#PBS -P hu38
#PBS -q normal
#PBS -l software=VinaCarb
#PBS -l wd

export VINA_CARB=../../VC_1_0

mkdir large_logs

for folder in large/*LIGAND*;
    do
        touch large_logs/log_$folder.txt
        ../../vina-carb --receptor large/$folder/*Without* --ligand large/$folder/*pdb.mol2* --config large/$folder/*.conf --out large/$folder/$folder.txt --log large/log_$folder.txt
    done

