#!/bin/bash 
#PBS -l walltime=48:00:00
#PBS -l ncpus=16
#PBS -l mem=3GB
#PBS -l jobfs=10GB
#PBS -P hu38
#PBS -q normal
#PBS -l software=VinaCarb
#PBS -l wd

export VINA_CARB=../../VC_1_0

for folder in small/*LIGAND*;
    touch $folder_log.txt
    touch folder_out.txt
    do
        ../../vina-carb --receptor $folder/*Without* --ligand $folder/*uncharged.pdb.pdbqt --config $folder/*.conf --out folder_out.txt --log $folder_log.txt
    done
    