#!/bin/bash 
#PBS -l walltime=120:00:00
#PBS -l ncpus=16
#PBS -l mem=3GB
#PBS -l jobfs=10GB
#PBS -P ho38
#PBS -q normal
#PBS -l software=VinaCarb
#PBS -l wd

export VINA_CARB=../../VC_1_0

mkdir logs

for folder in *LIGAND*;
    do
        touch logs/log_$folder.txt
        ../../vina-carb --receptor $folder/*Without* --ligand $folder/*pdb.mol2* --config $folder/*.conf --log logs/log_$folder.txt
    done

